x-logging: &default-logging
  driver: json-file
  options:
    max-size: "128m"
    max-file: "10"

x-resources: &default-resources
  limits: # ① a. 资源限制可根据算法占用情况决定
    cpus: "4"
    memory: 8G
#  reservations: # ① b. 不使用GPU直接去除
#    devices:
#      - driver: "nvidia"
#        count: "all"
#        # device_ids: ['0', '1']
#        capabilities: [ "gpu" ]


services:
  web:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile
      args:
        BASE_IMAGE: "ubuntu:26.04"
        # BASE_IMAGE: "nvidia/cuda:13.3.1-cudnn-devel-ubuntu26.04" # 按照项目需要是否使用CUDA镜像
        PYTHON_VERSION: "3.12" # 按照项目需要选择Python版本
        # ENABLE_CHINA_MIRROR: "true"  # 是否使用国内镜像。默认为true
    image: "alg_template:1.0"     # ②【修改：项目名】
    restart: unless-stopped
    environment:
      - PROFILE=test # ③ 若项目不分多环境(如test、prod)，可去除
    ports:
      - '23456:8080'   # ④ 注意修改端口
    extra_hosts:
      - "host.docker.internal:host-gateway" # 所在主机
      - "api.test.local:192.168.xxx.xxx" # 其他IP的域名映射
    # volumes:
    #   - /workspace/docker/volume/项目名/具体目录:/具体目录   # ⑤ 若使用Volume，使用公共数据目录映射
    deploy:
      resources: *default-resources
    logging: *default-logging

# docker compose build --progress=plain
# docker compose up -d
