x-logging: &default-logging
  driver: json-file
  options:
    max-size: "128m"
    max-file: "10"

x-resources: &default-resources
  limits:
    cpus: "8"
    memory: 16G
  reservations:
    devices:
      - driver: "nvidia"
        count: "all"
        capabilities: [ "gpu" ]

services:
  build_service:
    build:
      context: ../../../
      dockerfile: cuda-miniforge-ssh-zsh.Dockerfile
      args:
        # 修改镜像名 ①
        ORIGINAL_IMAGE: "alg:cuda11.8.0-cudnn8-devel-ubuntu22.04-miniforge"
      secrets: # 构建时候修改密码
        - root_password
        - user_password
    # 修改镜像名 ②
    image: "alg:cuda11.8.0-cudnn8-devel-ubuntu22.04-miniforge-ssh-zsh"
    restart: unless-stopped
    ports:
      - "22222:22"
    secrets: # 启动容器时候修改密码
      - root_password
      - user_password
    deploy:
      resources: *default-resources
    logging: *default-logging
    tty: true

secrets:
  root_password:
    file: ../../../build_config/root/secret/root_password.txt
  user_password:
    file: ../../../build_config/root/secret/user_password.txt

# BUILDKIT_PROGRESS=plain docker-compose build --no-cache
